### ISSUE TITLE
关于效果复现问题

### ISSUE THREAD

**Issue by DuTim** [cjx96/C2DSR#1]
非常好的工作! 但是在复现您模型时,发现:
   (1) Movie-Book scenario.场景下 book domain始终无法到达预期效果, 尝试了更换一些超参数效果也不理想,问一下对于复现任务2 需要什么样的参数调整或是其他.
![image](https://user-images.githubusercontent.com/50939742/201808962-aeb35582-0791-41fa-a9e7-6bf5f91b89d0.png)
![image](https://user-images.githubusercontent.com/50939742/201809096-06efa6d9-b48c-4e0c-9a99-af64262e18d2.png)

   (2) 在论文中提到Max_len=30, 模型中的Max_len 是超参数 但是在 loader.py lin 205-210 处又被手动固定, max_len在实验中按默认{15,30}即可吗?
![image](https://user-images.githubusercontent.com/50939742/201809870-f8fa76dd-577d-47df-9b62-6410330dd910.png)
非常感谢您公开代码, 期待 您的回复.

**Comment by cjx96** [comment]
Hi~, 非常感谢您关注我们的工作。

对于第一个问题，我印象中这个数据集确实有些难调，你可以用早停尝试一下其他参数情况，然后把更细粒度的epoch结果打印出来看看。

对于第二个问题，主要是因为不同数据集的序列平均长度不同，于是根据不同的序列长度就选择了不同大小的max_len。
