### ISSUE TITLE
关于对比方法MIFN的复现

### ISSUE THREAD

**Issue by orion-orion** [cjx96/C2DSR#2]
虽然这个问题不应该在这里提，但还是麻烦您解答一下了。就是您的对比方法里提到有MIFN（它的开源代码在这：https://github.com/mamuyang/MIFN ），但是我发现它的开源代码中数据集没有上传完全，导致复现难度很大，想请教下您是怎么复现该方法的，谢谢啦♪(･ω･)ﾉ

**Comment by cjx96** [comment]
Hi~，我当时是问原作者发邮件要的数据集，对于其中的KG部分，她把商品之间的一些关联都处理好了，主要包括also_buy, also_view, buy_together, buy_after_viewing这几类商品之间的关联。

**Comment by orion-orion** [comment]
呜呜呜，能再发我邮件一份吗？❤️谢谢啦：orion-orion@foxmail.com

**Comment by orion-orion** [comment]
您好，请问您有MIFN原作者的邮箱地址或其他联系方式吗？谢谢~或者分享下您复现的代码也行

**Comment by orion-orion** [comment]
您好，请问您有MIFN原作者的邮箱地址或其他联系方式吗？谢谢~或者分享下您复现的代码也行。

**Comment by orion-orion** [comment]
您好，请问您有MIFN原作者的邮箱地址或其他联系方式吗？谢谢~或者分享下您复现的代码也行🙏🏻。

**Comment by cjx96** [comment]
Hi~ I send it to your e-mail.

**Comment by orion-orion** [comment]
收到，非常感谢❤️
