### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by XXX-1310** [cjx96/C2DSR#3]
非常棒的工作，也十分感谢你们能够开源代码，但是在数据集处理的过程中有个疑问希望能够得到您的解答，就是在您提供的数据集中的Alist.txt这个文件，这个文件中最左边一列的index是指的什么呢？我尝试过和traindata_new.txt中的item index做匹配，发现并不一致。期待您的回复!!!

**Comment by cjx96** [comment]
具体原因我也不清楚，我是问原作者要的处理好的数据集，在这个基础上，我对数据集的划分做了一些改动。

**Comment by MuMuBai** [comment]
可以要一份原作者处理好的数据集吗？ 如果可以万分感谢  1191060861@qq.com
