### ISSUE TITLE
The creating of  negative_sample

### ISSUE THREAD

**Issue by DiMarzioBian** [cjx96/C2DSR#4]
Hi, I recently read your paper and currently trying to implement your code in my own tuning framework. Upon reading your code, I found that you are trying to sample a negative item list for each of the sequences at length 999. However, the final metric is calculated based on the 999 sampled items instead of the whole item set. May I know the reason for this operation?

**Comment by DiMarzioBian** [comment]
I also have re-written your project in my own framework with some improving, please check [here](https://github.com/DiMarzioBian/C2DSR).

**Comment by cjx96** [comment]
Hi~, thanks for your efforts in this work!

For the evaluation technique, we first conduct the experiments under the original leaked datasets, and find 10+ points improvements to MIFN. But in the next week, we notice the fatal information leak issue, thus we re-generate the datasets and re-run the experiments. Unsurprisingly, the test metrics are much lower than before, to make a trade-off, we utilize the leave-on-out technique[1,2] to calculate the metrics (which is widely used in various recommendation tasks).


[1] Progressive Self-Attention Network with Unsymmetrical Positional Encoding for Sequential Recommendation
[2]  Lighter and Better: Low-Rank Decomposed Self-Attention Networks for Next-Item Recommendation

**Comment by DiMarzioBian** [comment]
I understand you are adopting leave-one-out, but my question is at line 256 and 265 of ```C2DSR/C2DSR_src/model/trainer.py```. Why the rank is calculated based on the number of negative samples that have larger scores than the ground truth? Shouldn't it be calculated among all items' scores?

**Comment by cjx96** [comment]
From my understanding, the two different ways will obtain the same results?

**Comment by cjx96** [comment]
For the question: Shouldn't it be calculated among all items' scores? 

If we do without leave-one-out technique, that is the right way to evaluate the model performance.

**Comment by DiMarzioBian** [comment]
From my understanding, leave-one-out in sequential recommendation is to take out last 2 interactions of a sequence out for validation and testing, which is different from leave-one-out in cross validation. 

Check [SASRec](SASRec: Self-Attentive Sequential Recommendation) and its [implementation](https://github.com/pmixer/SASRec.pytorch).

Secondly, in your code, if you sample more negative items, the results will get worse, and it will also change if you use a different seed. In my opinion, it is counterintuitive and unfair.

Please correct me if I am wrong.

**Comment by DiMarzioBian** [comment]
[SASRec: Self-Attentive Sequential Recommendation](https://cseweb.ucsd.edu/~jmcauley/pdfs/icdm18.pdf)

**Comment by cjx96** [comment]
Hi~ For the first question: take out last 2 interactions of a sequence out for validation and testing.

Answer: I also tried this setting, however, the split rate is not satisfied in the cross-domain setting(consider XorY as the last one or two positions), thus I using another way (the last one items are divided valid/test equally).


For the second question: it is counterintuitive and unfair.

Answer: As I know, the leave-one-out technique is seriously affected by the negative sampling number, especially under the setting negative sampling number = 99. Thus, some works[1] discussed this issue, and suggested setting the number=999 to alleviate it. In this 999 setting, if you change the seed, the experimental result will float within an acceptable range.

[1] On sampled metrics for item recommendation

**Comment by cjx96** [comment]
I acknowledge utilizing the "approximate" leave-one-out method to estimate the performance (under the 1000-item-prediction instead of the full-item-prediction).
