### ISSUE TITLE
关于代码复现效果

### ISSUE THREAD

**Issue by dominate999** [cjx96/C2DSR#7]
作者您好！我最近在复现代码时，按照您给出的脚本在Food-Kicthen数据跑出来的结果达不到论文中提到的效果，想请问下在这个数据集上也需要进行调参吗？能否给出调整后的参数呢？
运行环境：
pytorch 1.6
Tesla V100-PCIE-32GB

以下是我使用默认的参数跑出来的结果：
![image](https://github.com/cjx96/C2DSR/assets/64464830/559b8431-4922-4de0-8e6f-d8f91b22afd7)
![image](https://github.com/cjx96/C2DSR/assets/64464830/af5feb2f-f2f8-4546-b13a-ae176e702d39)
![image](https://github.com/cjx96/C2DSR/assets/64464830/403fdbdf-d177-4c0e-83d1-9fbbdc6639b2)
其中FK，MB均没达到论文的效果，但是EE上表现比论文上要好
#1 这个issue中提到了Movie-book需要进行调参。

**Comment by dominate999** [comment]
作者在邮件已回复：”你好，我当时也是调了好几组不同的参数值，建议你也多尝试几组不同参数。"

**Comment by glaucus04** [comment]
> 作者您好！我最近在复现代码时，按照您给出的脚本在Food-Kicthen数据跑出来的结果达不到论文中提到的效果，想请问下在这个数据集上也需要进行调参吗？能否给出调整后的参数呢？ 运行环境： pytorch 1.6 Tesla V100-PCIE-32GB
> 
> 以下是我使用默认的参数跑出来的结果： ![image](https://private-user-images.githubusercontent.com/64464830/283079694-559b8431-4922-4de0-8e6f-d8f91b22afd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNTA5MzUsIm5iZiI6MTcxMDM1MDYzNSwicGF0aCI6Ii82NDQ2NDgzMC8yODMwNzk2OTQtNTU5Yjg0MzEtNDkyMi00ZGUwLThlNmYtZDhmOTFiMjJhZmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE3MjM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkOGQ3MzZkMjI1NTU0NzE4Yzg2YTA4OGM3ODA3YjU0ZGQ3Y2M1YTliOGZkYjhjYzhmNmJmMzgzZTEyZjQxOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6fP_XE-m6qhTGq6AuXYEbJqXXcjdKBMmBgI4BhbRKPY) ![image](https://private-user-images.githubusercontent.com/64464830/283079786-af5feb2f-f2f8-4546-b13a-ae176e702d39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNTA5MzUsIm5iZiI6MTcxMDM1MDYzNSwicGF0aCI6Ii82NDQ2NDgzMC8yODMwNzk3ODYtYWY1ZmViMmYtZjJmOC00NTQ2LWIxM2EtYWUxNzZlNzAyZDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE3MjM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlODg1MTU0NDNmYmNmMDY2MmMwMTZjYzU0NzU0MmUzNTgwYWUyMTFkZDBiN2Y2Mzc5NDcxYmRlYzU3NDNhZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hypkaPQi_8AvLH-77HQ9_oAJfS_zMI12qDZYNrOJSSc) ![image](https://private-user-images.githubusercontent.com/64464830/283079828-403fdbdf-d177-4c0e-83d1-9fbbdc6639b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNTA5MzUsIm5iZiI6MTcxMDM1MDYzNSwicGF0aCI6Ii82NDQ2NDgzMC8yODMwNzk4MjgtNDAzZmRiZGYtZDE3Ny00YzBlLTgzZDEtOWZiYmRjNjYzOWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE3MjM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZTRjYmI0YWI3MTU5OWUwOTdiNTAxNzMwMWY1Y2U3Njg1YWUxNGRlMjc5MjMyMDk2MmQ2MmY1YTc0MGE5MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qeQEyqZLdhEpu3k36v3SVNA1Ph3TWRN2WHO4sinzrRQ) 其中FK，MB均没达到论文的效果，但是EE上表现比论文上要好 #1 这个issue中提到了Movie-book需要进行调参。

您好，最近复现的时候发现ee数据有部分缺失，请问方便发我一份ee的数据集方便发我一份吗， 601059745@qq.com谢谢！
